kind: Pod
apiVersion: v1
metadata:
  name: elastic
  namespace: zasu
spec:
  volumes:
    - name: elog
      persistentVolumeClaim:
       claimName: elog
    - name: edata
      persistentVolumeClaim:
       claimName: edata
  containers:
    - name: elastic
      image: grafpoo/elasticsearch-1.2.1-java-8:initial
      ports:
        - containerPort: 9200
          name: http
      volumeMounts:
        - name: edata
          mountPath: /elasticsearch-1.2.1/data
        - name: elog
          mountPath: /elasticsearch-1.2.1/logs
