apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: small-dyno

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: small-dyno
