apiVersion: v1
kind: Service
metadata:
  name: elastic
  labels:
    app: elasticsearch
    service: elastic
  annotations:
    'prometheus.io/scrape': 'true'
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch
    service: elastic
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: elastic
  labels:
    app: elasticsearch
    service: elastic
spec:
  serviceName: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        service: elastic
    spec:
      volumeMounts:
      - name: elog
        persistentVolumeClaim:
          claimName: elog
      - name: edata
        persistentVolumeClaim:
          claimName: edata
      containers:
      - name: elastic
        image: grafpoo/elasticsearch-1.2.1-java-8:initial
        ports:
        - name: http
          containerPort: 9200
        volumeMounts:
        - name: edata
          mountPath: /elasticsearch-1.2.1/data
        - name: elog
          mountPath: /elasticsearch-1.2.1/logs
      restartPolicy: Always
